-- Minimal POC error reporting. The app may insert reports with its anon key, but
-- cannot read them back. Review reports in Supabase Dashboard > Table Editor.

create table if not exists public.error_logs (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  reference   text not null,
  user_id     text,
  user_role   text,
  error_name  text not null,
  message     text not null,
  stack       text,
  screen      text,
  platform    text,
  app_version text,
  context     jsonb not null default '{}'::jsonb,
  resolved    boolean not null default false,
  notes       text
);

create unique index if not exists error_logs_reference_idx
  on public.error_logs (reference);
create index if not exists error_logs_created_at_idx
  on public.error_logs (created_at desc);

alter table public.error_logs enable row level security;
drop policy if exists error_logs_anon_insert on public.error_logs;
create policy error_logs_anon_insert
  on public.error_logs for insert to anon
  with check (true);

-- Deliberately no anon SELECT/UPDATE/DELETE policy. The anon key is embedded in the
-- app, so allowing reads would expose every user's stack traces and diagnostic data.
